### ISSUE TITLE
chain.append(...) возвращает одни и те же наборы сообщений с разными offcet

### ISSUE THREAD

**Issue by nanshakov** [VKCOM/node-vk-call#5]
Имеем следующий код
`async function getMessageFromDialog(userId, count, offcet, api) {
    if (count == -1)
        return new Array();
    var chain = api.chain();
    chain.append("messages.getHistory", { count: 200, user_id: userId, offcet: 200 });
    chain.append("messages.getHistory", { count: 200, user_id: userId, offcet: 400 });
    ....
    chain.append("messages.getHistory", { count: offcet, user_id: userId, offcet: offcet * 24 });
    chain.done().then((result) =>
    {
            var anser = new Array();
            for (var i = 0; i < result.length; i++) 
            {
                anser.push(result[i]);
            }
            if(count >= 0)
                return anser.push(getMessageFromDialog(userId, count - 1, offcet * 26, api));
        });`
который должен рекурсивно получать историю из диалога.
То, что возвращает код - на двух скриншотах ниже, показываю 0 и 1 элементы массива.
https://yadi.sk/i/FqLMXo8d3NJeYG
https://yadi.sk/i/qOtpAIiF3NJeZJ
Как видно, id сообщений одинаковый, и код работает не правильно. При этом, если повторить в браузере запрос с такими же параметрами - https://yadi.sk/i/19NagvZi3NJf2M все работает.
node v8.5.0

**Comment by borapop** [comment]
@nanshakov параметра offcet в VK API нет, есть offset
